App\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            message: 'There is already an account with this email'
    properties:
        email:
            - NotBlank: ~
            - Email:
                  message: The email "{{ value }}" is not a valid email.

App\Entity\Role:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name]
            message: 'There is already a role with this name'
    properties:
        name:
            - NotBlank: ~

App\Entity\Permission:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name]
            message: 'There is already a permission with this name'
    properties:
        name:
            - NotBlank: ~