App\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            message: 'There is already an account with this email'
    properties:
        email:
            - NotBlank: ~