index:
    path: /
    controller: App\Controller\DefaultController::index

app_register:
     path: /register
     controller: App\Controller\RegistrationController::register

app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    
app_logout:
    path: /logout
    methods: GET

app_admin:
    path: /admin
    controller: App\Controller\AdminController::index

app_admin_security:
    path: /admin/security
    controller: App\Controller\AdminController::security
    
app_admin_security_user:
    path: /admin/security/users
    controller: App\Controller\AdminController::userList

app_admin_security_user_manage:
    path: /admin/security/users/{id}/manage
    controller: App\Controller\AdminController::userManage
    
app_admin_security_user_manage_activate:
    path: /admin/security/users/{id}/manage/activate
    controller: App\Controller\AdminController::userActivate

app_admin_security_user_manage_deactivate:
    path: /admin/security/users/{id}/manage/deactivate
    controller: App\Controller\AdminController::userDeactivate

app_admin_security_role:
    path: /admin/security/roles
    controller: App\Controller\AdminController::role

app_admin_security_role_create:
    path: /admin/security/roles/create
    controller: App\Controller\AdminController::createRole

app_admin_security_permission:
    path: /admin/security/permissions
    controller: App\Controller\AdminController::permission

app_admin_security_permission_create:
    path: /admin/security/permissions/create
    controller: App\Controller\AdminController::createPermission

app_admin_security_permission_delete:
    path: /admin/security/permissions/{id}/delete
    controller: App\Controller\AdminController::deletePermission

app_admin_security_role_manage:
    path: /admin/security/roles/{id}/manage
    controller: App\Controller\AdminController::roleManage

app_admin_security_role_manage_attach_permission:
    path: /admin/security/roles/{id}/manage/attach-permissions
    controller: App\Controller\AdminController::permissionAttach

app_admin_security_role_manage_detach_permission:
    path: /admin/security/roles/{role_id}/manage/detach-permission/{permission_id}
    controller: App\Controller\AdminController::detachPermission

app_product_panel:
    path: /product-panel
    controller: App\Controller\ProductController::index

app_product_panel_team:
    path: /product-panel/teams
    controller: App\Controller\ProductController::team

app_product_panel_team_create:
    path: /product-panel/teams/create
    controller: App\Controller\ProductController::createTeam

app_product_panel_team_manage:
    path: /product-panel/teams/{id}/manage
    controller: App\Controller\ProductController::manage

app_product_panel_team_manage_add_member:
    path: /product-panel/teams/{id}/manage/add-member
    controller: App\Controller\ProductController::addMember

app_product_panel_team_manage_delete_member:
    path: /product-panel/teams/{team_id}/manage/delete-member/{member_id}
    controller: App\Controller\ProductController::deleteTeamMember
