index:
    path: /
    controller: App\Controller\DefaultController::index

app_register:
     path: /register
     controller: App\Controller\RegistrationController::register

app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    
app_logout:
    path: /logout
    methods: GET

app_admin:
    path: /admin
    controller: App\Controller\AdminController::index

app_admin_security:
    path: /admin/security
    controller: App\Controller\AdminController::security

app_admin_security_role:
    path: /admin/security/roles
    controller: App\Controller\AdminController::role

app_admin_security_role_create:
    path: /admin/security/roles/create
    controller: App\Controller\AdminController::createRole

app_admin_security_permission:
    path: /admin/security/permissions
    controller: App\Controller\AdminController::permission

app_admin_security_permission_create:
    path: /admin/security/permissions/create
    controller: App\Controller\AdminController::createPermission

app_admin_security_permission_delete:
    path: /admin/security/permissions/{id}/delete
    controller: App\Controller\AdminController::deletePermission

app_admin_security_role_manage:
    path: /admin/security/roles/{id}/manage
    controller: App\Controller\AdminController::roleManage

app_admin_security_role_manage_attach_permission:
    path: /admin/security/roles/{id}/manage/attach-permissions
    controller: App\Controller\AdminController::permissionAttach