App\Entity\PasswordRecovery:
    type: entity
    repositoryClass: App\Repository\PasswordRecoveryRepository
    table: password_recovery
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            length: 255
            nullable: false
            unique: true
        token:
            type: string
            length: 255
            nullable: false
        created:
            type: datetime
            nullable: false
        
