App\Entity\Project:
    type: entity
    repositoryClass: App\Repository\ProjectRepository
    table: project
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
            nullable: false
            unique: false
        description:
            type: string
            length: 255
            nullable: false
            unique: false
    manyToOne:
        team:
            targetEntity: App\Entity\Team
            inversedBy: projects
            joinColumn:
                name: team_id
                referencedColumnName: id