App\Entity\Task:
    type: entity
    repositoryClass: App\Repository\TaskRepository
    table: task
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
            nullable: false
            unique: false
        description:
            type: string
            length: 10000
            nullable: false
            unique: false
        status:
            type: integer
            length: 20
            nullable: false
            options:
                default: 1
        created_at:
            type: datetime
            options:
                default: CURRENT_TIMESTAMP
    manyToOne:
        executor:
            targetEntity: App\Entity\User
            inversedBy: tasks
            joinColumn:
                nullable: false
                name: executor_id
                referencedColumnName: id
        team:
            targetEntity: App\Entity\Team
            inversedBy: tasks
            joinColumn:
                nullable: false
                name: team_id
                referencedColumnName: id
        project:
            targetEntity: App\Entity\Project
            inversedBy: tasks
            joinColumn:
                nullable: false
                name: project_id
                referencedColumnName: id
        author:
            targetEntity: App\Entity\User
            inversedBy: myTasks
            joinColumn:
                nullable: false
                name: author_id
                referencedColumnName: id
    oneToMany:
        rates:
            targetEntity: App\Entity\RateInfo
            mappedBy: task
            cascade: [remove]
