App\Entity\Team:
    type: entity
    repositoryClass: App\Repository\TeamRepository
    table: team
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
            nullable: false
            unique: false
        description:
            type: string
            length: 255
            nullable: false
            unique: false
    manyToMany:
        members:
            targetEntity: App\Entity\User
            mappedBy: teams
    oneToMany:
        projects:
            targetEntity: App\Entity\Project
            mappedBy: team
        tasks:
            targetEntity: App\Entity\Task
            mappedBy: team