App\Entity\User:
    type: entity
    repositoryClass: App\Repository\UserRepository
    table: "`user`"
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            length: 180
            nullable: false
            unique: true
        password:
            type: string
            nullable: false
            unique: false
        status:
            type: integer
            length: 25
            nullable: false
            unique: false
            options:
                default: 0
                comment: user's status 
    manyToMany:
        roles:
            targetEntity: App\Entity\Role
            inversedBy: users
            cascade: [ persist ]
            joinTable:
                name: user_role
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id
        teams:
            targetEntity: App\Entity\Team
            inversedBy: members
            cascade: [ persist ]
            joinTable:
                name: member_team
                joinColumns:
                    member_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    team_id:
                        referencedColumnName: id
    oneToMany:
        tasks:
            targetEntity: App\Entity\Task
            mappedBy: executor
        projects:
            targetEntity: App\Entity\Project
            mappedBy: customer
        myTasks:
            targetEntity: App\Entity\Task
            mappedBy: author
        myProjects:
            targetEntity: App\Entity\Project
            mappedBy: owner
        rates:
            targetEntity: App\Entity\RateInfo
            mappedBy: user
        authorRates:
           targetEntity: App\Entity\RateInfo
           mappedBy: author
        myTeams:
            targetEntity: App\Entity\Team
            mappedBy: owner
